"""empty message

Revision ID: 0f7029927d46
Revises: ccb05daae699
Create Date: 2018-03-15 19:03:09.200518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f7029927d46'
down_revision = 'ccb05daae699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['bom_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_result_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['bom_result.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_result_beam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['bom_result_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_result_missing_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=64), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['bom_result_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_result_beam_part',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=64), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('beam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beam_id'], ['bom_result_beam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom_result_beam_part')
    op.drop_table('bom_result_missing_part')
    op.drop_table('bom_result_beam')
    op.drop_table('bom_result_material')
    op.drop_table('bom_result')
    # ### end Alembic commands ###
