"""empty message

Revision ID: b0a7989106c9
Revises: 0f7029927d46
Create Date: 2018-03-15 20:11:12.179957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a7989106c9'
down_revision = '0f7029927d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bom_result_beam', sa.Column('waste', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bom_result_beam', 'waste')
    # ### end Alembic commands ###
