"""empty message

Revision ID: ccb05daae699
Revises: 
Create Date: 2018-03-10 19:13:40.758787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb05daae699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('size')
    )
    op.create_table('material_length',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('length')
    )
    op.create_table('bom_file_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_no', sa.String(length=64), nullable=True),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('BB_length', sa.Float(), nullable=True),
    sa.Column('BB_width', sa.Float(), nullable=True),
    sa.Column('BB_thickness', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['bom_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bom_session_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['bom_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_size_lengths',
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.Column('length_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['length_id'], ['material_length.id'], ),
    sa.ForeignKeyConstraint(['size_id'], ['material.id'], ),
    sa.PrimaryKeyConstraint('size_id', 'length_id')
    )
    op.create_table('bom_session_length',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('size_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['size_id'], ['bom_session_size.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom_session_length')
    op.drop_table('material_size_lengths')
    op.drop_table('bom_session_size')
    op.drop_table('bom_file_contents')
    op.drop_table('material_length')
    op.drop_table('material')
    op.drop_table('bom_session')
    op.drop_table('bom_files')
    # ### end Alembic commands ###
